{
 "title": "url-shortener",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Links count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "url_shortener_links_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Count of 5xx",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (increase(axum_http_requests_total{endpoint!=\"/metrics\", status=~\"5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(axum_http_requests_total{endpoint!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Performance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 *\nhistogram_quantile(\n  0.50,\n  sum by (le) (\n    rate(\n      axum_http_requests_duration_seconds_bucket{\n        endpoint!=\"/metrics\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "P50"
    },
    {
     "expr": "1000 *\nhistogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(\n      axum_http_requests_duration_seconds_bucket{\n        endpoint!=\"/metrics\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "1000 *\nhistogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(\n      axum_http_requests_duration_seconds_bucket{\n        endpoint!=\"/metrics\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "RPS by status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(status) (rate(axum_http_requests_total{endpoint!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}